const baseEvent = {
  schema_version: "1.0",
  execution_id: "exec-original-8271",
  trace_id: "trace-8271",
  replay_run_id: undefined,
  logical_operation_id: "checkout-8271",
} as const;

const events = [
  {
    ...baseEvent,
    event_id: "evt-gateway-start",
    parent_event_id: undefined,
    component: { name: "gateway", instance: "gateway-1" },
    operation: { name: "POST /checkout", kind: "ENTRYPOINT" },
    event_type: "START",
    attempt: 1,
    occurred_at: "2026-08-29T10:32:01.000Z",
    sequence: 0,
    status: "RUNNING",
    attributes: {},
  },
  {
    ...baseEvent,
    event_id: "evt-checkout-start",
    parent_event_id: "evt-gateway-start",
    component: { name: "checkout", instance: "checkout-1" },
    operation: { name: "checkout", kind: "INTERNAL" },
    event_type: "START",
    attempt: 1,
    occurred_at: "2026-08-29T10:32:01.004Z",
    sequence: 1,
    status: "RUNNING",
    attributes: { checkout_timeout_ms: 200 },
  },
  {
    ...baseEvent,
    event_id: "evt-payment-1-start",
    parent_event_id: "evt-checkout-start",
    component: { name: "payment", instance: "payment-1" },
    operation: { name: "authorize", kind: "DEPENDENCY" },
    event_type: "START",
    attempt: 1,
    occurred_at: "2026-08-29T10:32:01.015Z",
    sequence: 1,
    status: "RUNNING",
    attributes: { configured_latency_ms: 350, dependency_name: "payment_simulator" },
  },
  {
    ...baseEvent,
    event_id: "evt-timeout",
    parent_event_id: "evt-checkout-start",
    component: { name: "checkout", instance: "checkout-1" },
    operation: { name: "payment-timeout", kind: "CONTROL" },
    event_type: "TIMEOUT",
    attempt: 1,
    occurred_at: "2026-08-29T10:32:01.204Z",
    sequence: 2,
    duration_ms: 200,
    status: "TIMEOUT",
    attributes: { checkout_timeout_ms: 200 },
  },
  {
    ...baseEvent,
    event_id: "evt-retry",
    parent_event_id: "evt-checkout-start",
    component: { name: "checkout", instance: "checkout-1" },
    operation: { name: "retry-payment", kind: "CONTROL" },
    event_type: "RETRY",
    attempt: 1,
    occurred_at: "2026-08-29T10:32:01.205Z",
    sequence: 3,
    status: "SUCCESS",
    attributes: {},
  },
  {
    ...baseEvent,
    event_id: "evt-payment-2-start",
    parent_event_id: "evt-checkout-start",
    component: { name: "payment", instance: "payment-1" },
    operation: { name: "authorize", kind: "DEPENDENCY" },
    event_type: "START",
    attempt: 2,
    occurred_at: "2026-08-29T10:32:01.210Z",
    sequence: 2,
    status: "RUNNING",
    attributes: { configured_latency_ms: 350, dependency_name: "payment_simulator" },
  },
  {
    ...baseEvent,
    event_id: "evt-ledger-1",
    parent_event_id: "evt-payment-1-start",
    component: { name: "ledger", instance: "ledger-1" },
    operation: { name: "commit", kind: "SIDE_EFFECT" },
    event_type: "EFFECT",
    attempt: 1,
    occurred_at: "2026-08-29T10:32:01.365Z",
    sequence: 1,
    status: "SUCCESS",
    attributes: { effect_id: "ledger-effect-1", effect_committed: true },
  },
  {
    ...baseEvent,
    event_id: "evt-ledger-2",
    parent_event_id: "evt-payment-2-start",
    component: { name: "ledger", instance: "ledger-1" },
    operation: { name: "commit", kind: "SIDE_EFFECT" },
    event_type: "EFFECT",
    attempt: 2,
    occurred_at: "2026-08-29T10:32:01.560Z",
    sequence: 2,
    status: "SUCCESS",
    attributes: { effect_id: "ledger-effect-2", effect_committed: true },
  },
] as const;

const incident = {
  schema_version: "1.0",
  incident_id: "inc-8271",
  status: "READY",
  failure_oracle: { id: "duplicate_ledger_effect", version: "1.0.0" },
  system_pack: { id: "checkout_duplicate_effect", version: "1.0.0", interface_version: "1.0" },
  trace_id: "trace-8271",
  execution_id: "exec-original-8271",
  detected_at: "2026-08-29T10:32:01.561Z",
  summary: "Timeout-driven retry committed two ledger effects for checkout-8271.",
  evidence_event_ids: ["evt-timeout", "evt-retry", "evt-ledger-1", "evt-ledger-2"],
  graph_id: "graph-8271",
  sanitization_status: "PASS",
} as const;

export const developmentIncidentList = {
  items: [incident],
} as const;

export const developmentIncidentDetail = {
  incident,
  graph: {
    schema_version: "1.0",
    graph_id: "graph-8271",
    incident_id: "inc-8271",
    ordering_policy_version: "1.0",
    nodes: events.map((event, timeline_index) => ({ event_id: event.event_id, timeline_index })),
    edges: [
      { edge_id: "edge-gateway-checkout", from_event_id: "evt-gateway-start", to_event_id: "evt-checkout-start", type: "PARENT_CHILD" },
      { edge_id: "edge-checkout-payment", from_event_id: "evt-checkout-start", to_event_id: "evt-payment-1-start", type: "DEPENDENCY" },
      { edge_id: "edge-timeout", from_event_id: "evt-payment-1-start", to_event_id: "evt-timeout", type: "TEMPORAL" },
      { edge_id: "edge-retry", from_event_id: "evt-timeout", to_event_id: "evt-retry", type: "RETRY" },
      { edge_id: "edge-attempt-two", from_event_id: "evt-retry", to_event_id: "evt-payment-2-start", type: "RETRY" },
      { edge_id: "edge-effect-one", from_event_id: "evt-payment-1-start", to_event_id: "evt-ledger-1", type: "SIDE_EFFECT" },
      { edge_id: "edge-effect-two", from_event_id: "evt-payment-2-start", to_event_id: "evt-ledger-2", type: "SIDE_EFFECT" },
    ],
  },
  events,
} as const;
